# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllable', models.CharField(max_length=20)),
                ('previous_syllable', models.CharField(max_length=20)),
                ('syllable_index', models.IntegerField(default=0)),
                ('number_of_syllables', models.IntegerField(default=0)),
                ('count_syllable', models.IntegerField(default=0)),
            ],
        ),
    ]
