# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:25
from __future__ import unicode_literals

from django.db import migrations


from words.syllable import get_index_table, get_syllable_list


def filling_database(apps, schema_editor):
    index_table = get_index_table(get_syllable_list('words/freqrnc2011.csv'))
    IndexTable = apps.get_model('words', 'IndexTable')
    for syllable_params in index_table:
        s = IndexTable(
            syllable=syllable_params[0],
            previous_syllable=syllable_params[1],
            syllable_index=syllable_params[2],
            number_of_syllables=syllable_params[3],
            count_syllable=syllable_params[4]
        )
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(filling_database),
    ]
