# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0002_auto_20171003_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudoWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='add date')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
