# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_pseudoword'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
    ]
